%global gitdate 20150812

Name:           envytools
Version:        0.0
Release:        0.3.git%{gitdate}%{?dist}
Summary:        Tools for people envious of nvidia's blob driver
License:        MIT
URL:            https://github.com/envytools/envytools
# Generated by make-git-snapshot.sh
Source0:        envytools-%{gitdate}.tar.bz2
Source1:        make-git-snapshot.sh
BuildRequires:  cmake flex bison
BuildRequires:  libpciaccess-devel libX11-devel libXext-devel libseccomp-devel
BuildRequires:  libxml2-devel libvdpau-devel libdrm-devel python3-devel

%description
Envytools contains a number of tools used for debugging / development of
the nouveau driver:

envydis: Disassembler and assembler for various ISAs found on nvidia GPUs
nvbios:  Tools to decode the card description structures found in nvidia VBIOS
nva:     Tools to directly access the GPU registers
vstream: Tools to decode and encode raw video bitstreams


%package        hwdocs
Summary:        Nouveau hardware documentation
BuildArch:      noarch

%description    hwdocs
The %{name}-hwdocs package contains hardware documentation for video
hardware supported by the nouveau driver project.


%prep
%setup -q -n %{name}-%{gitdate}


%build
%cmake -DBUILD_SHARED_LIBS:BOOL=OFF .
make %{?_smp_mflags}


%install
%make_install
cp -p COPYING $RPM_BUILD_ROOT%{_docdir}/%{name}
# Remove the tools for rules-ng-ng XML register db manipulation
rm $RPM_BUILD_ROOT%{_bindir}/headergen
rm $RPM_BUILD_ROOT%{_bindir}/lookup
# Remove hwtest this really is for developers only
rm $RPM_BUILD_ROOT%{_bindir}/hwtest
# We do not want the libs (these are for internal use only)
rm $RPM_BUILD_ROOT%{_libdir}/*.a
rm -r $RPM_BUILD_ROOT%{_includedir}/%{name}
# Remove the python scripts used to generate the docs
rm $RPM_BUILD_ROOT%{_docdir}/%{name}/hwdocs/*.py


%files
%doc %dir %{_docdir}/%{name}
%license %{_docdir}/%{name}/COPYING
%doc %{_docdir}/%{name}/README*
%{_bindir}/de*
%{_bindir}/dumpstruct
%{_bindir}/envy*
%{_bindir}/evotiming
%{_bindir}/mmt_*
%{_bindir}/nv01*
%{_bindir}/nva*
%{_bindir}/nvbios
%{_bindir}/vdpow
%{_datadir}/rnndb

%files hwdocs
%doc %dir %{_docdir}/%{name}
%doc %{_docdir}/%{name}/hwdocs


%changelog
* Wed Aug 12 2015 Hans de Goede <hdegoede@redhat.com> - 0.0-0.3.git20150812
- New 20150812 git snapshot
- Add demmio to packaged binaries

* Tue Jun 23 2015 Hans de Goede <hdegoede@redhat.com> - 0.0-0.2.git20150622
- Packaging improvements from package-review (rhbz#1234468)
 - Mark COPYING as %%license
 - Put the hwdocs in their own -hwdocs subpackage
 - Use %%global instead of %%define

* Mon Jun 22 2015 Hans de Goede <hdegoede@redhat.com> - 0.0-0.1.git20150622
- Initial Fedora package
